### PR TITLE
Add isActive function and pageSize option

### PR DESCRIPTION
**Pull request by railapex**
Add isActive function option so dates can be dynamically inactivated
Add pageSize option to control how far to jump on paging forward/backward

Also, fix package scripts so things build better.

### CODE REVIEW

**Comment by railapex** [comment]
Also added support for dayClass function option to add dynamic classes to days.

**Comment by eduludi** [comment]
Nice work! Would you like to explain a little more about the isActive option? (So I can document that in the README). Thank you :)

**Comment by railapex** [comment]
Sure.

isActive is a function you can pass in on the options that will get called for each day and passed the date. You can return true or false as to whether the date should be active or not (get the active css class applied). This is basically an enhancement of the minDate/maxDate options that lets you set the active class separately for each date, rather than just starting at minDate or ending at maxDate.

If you do something like:

``` javascript
        var unavailable = [
           { Arrival: new Date(2015, 12, 1), Departure: new Date(2015, 12, 10) },
           { Arrival: new Date(2015, 10, 3), Departure: new Date(2015, 10, 4) }
        ];

        $('#calendar').yacal({
            isActive: function(date)
            {
                for (var i = 0; i < unavailable.length; i++)
                {
                    if (date.valueOf() >= unavailable[i].Arrival).valueOf() && date.valueOf() <= unavailable[i].valueOf())
                        return false;
                }

                return true;
            }
         });
```

Then you see why it is useful to have a setting of active based on each specific day.

**Comment by railapex** [comment]
dayClass function is similar, but adds additional custom classes that you return.

``` javascript
$('#calendar').yacal({
            dayClass: function(date)
            {
                 if (date.getDate() % 2)
                     return "odd";
                 else
                     return "even";
            });
         });
```

Now, theoretically, you could actually collapse all of this into one function. If you have the dayClass function, you could allow users to implement their own minDate/maxDate/isActive settings inside that and make the code simpler. I opted to add them as new features -- that all depends on your simplicity vs. ease of use line.

**Comment by eduludi** [comment]
Ok, this has been merged.

**Pull request closed without merging**
